name: CI

on:
  push: 
    branches: [main, dev, stg]
  pull_request:
    branches: [main, dev, stg]
  
jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js ${{ matrix.node-verison }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-verison }}
        
      - run: npm lint
      - run: npm test
      - run: npm run build --if-present